### ISSUE TITLE
Add translucent brush options

### ISSUE THREAD

**Issue by pescamillam** [ZMYaro/paintz#92] opened 2018-08-07 03:13 UTC

**Comment by ZMYaro** [comment] 2018-08-07 15:36
As far as I am aware, MS Paint does not have alpha for colors, so I am inclined to call this out of the scope of the project.

**Comment by ParodyVerse** [comment] 2018-11-28 16:33
Actually, there is a tool for that. It's called marker mode for the curve tool.

**Comment by ZMYaro** [comment] 2018-11-28 19:02
@ParodyVerse: Are you talking about the alternate brushes in Win7 Paint, or something else?

**Comment by ParodyVerse** [comment] 2018-11-28 19:31
in the toolbar, to the left of the colors, there are two drop-down menus, one for the outline, and one for the fill. there are a number of fill-types, including marker. the marker is what I'm talking about.

**Comment by ZMYaro** [comment] 2018-11-28 19:35
Ah, OK.  I hadn't prioritized those because I was prioritizing classic MS Paint features over Win7 Paint ones, but I will keep this ticket open for if/when I have time to work on those.

**Comment by ParodyVerse** [comment] 2018-11-28 19:36
Okay.

**Comment by ZMYaro** [comment] 2019-06-18 22:35
I just realized while going through old tickets there has actually been one open for this for a while 🤦.

**Comment by ZMYaro** [comment] 2019-06-18 22:35
Duplicate of https://github.com/ZMYaro/paintz/issues/42.

**Closed by ZMYaro** 2019-06-18 22:35 UTC
Labels: duplicate
