### ISSUE TITLE
Please allow users to easily change the ppi of the image they are working with.

### ISSUE THREAD

**Issue by Merlyn78** [zmyaro/paintz#280] opened 2024-07-23 04:40 UTC
**Is your feature request related to a problem?  Please describe.**
I am trying to republish a book, but my publisher's distributor requires my cover image to be at least 150 ppi.  Currently, my image is only about 92 ppi or less.  Your program does not allow me to edit this in any way.

**Describe the solution you would like**
Please create an ability to change an image's ppi in a quick and easy way.

**Describe alternatives you have considered**
I have tried simply resizing and saving the image to no avail.  I have also tried another program called Windows Paint.  I have read that this can be completed very easily with Photoshop, but I do not have the means, right now, to afford Photoshop.

**Additional context**
You could, possibly, put a display of the current ppi of the image being worked with on the bottom of the screen, next to the length and width configurations, and make that able to be changed by the user.

**Comment by ZMYaro** [comment] 2024-07-23 16:51
Marking this as a duplicate of #265.

Please note setting the pixels per inch (PPI)/dots per inch (DPI) of an image file is only metadata; it doesn't change anything about the actual image!  It is important to know the PPI you expect to print at to know how big your image needs to be, but the size of your image will be in **pixels**.

For instance, if you were printing an image on an 8.5- by 11-inch page at 150 PPI, then you would need an image 1,275 by 1,650 pixels:
$\textsf{8.5 inches} \times \frac{\textsf{150 pixels}}{\textsf{1  inch}} = \textsf{1,275 pixels}$
$\textsf{11 inches} \times \frac{\textsf{150 pixels}}{\textsf{1 inch}} = \textsf{1,650 pixels}$

I hope that helps!

**Closed as not planned** 2024-07-23 16:52 UTC
Labels: duplicate

**Comment by Merlyn78** [comment] 2024-07-23 22:58
Yes, that does help a LOT.  Thanks!

**Comment by ZMYaro** [comment] 2024-07-23 23:11
You're welcome!  Glad to help!
