### ISSUE TITLE
Fractional drop-shadows on palette looks overly sharp.

### ISSUE THREAD

**Issue by djrenren** [ZMYaro/paintz#109] opened 2018-11-29 20:31 UTC
**Describe the bug**
The small white drop shadow around palette colors causes rough edges and uneven rendering across browsers:

OSX-Firefox:
<img width="242" alt="image" src="https://user-images.githubusercontent.com/634666/49249969-82539e80-f3d2-11e8-9ee5-3e82e1f131bb.png">

OSX-Safari:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/634666/49249985-8ed7f700-f3d2-11e8-8148-f6c534ea99e8.png">

OSX-Chrome:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/634666/49250003-9d261300-f3d2-11e8-831b-ebc9d6651015.png">

While Chrome looks the closest to ok, the black pallet still looks a little rough.

**Comment by ZMYaro** [comment] 2018-11-29 20:33
@djrenren: Aside from increasing the outline (shadow) size in those (or all) browsers, do you have any other suggestions?

**Comment by ZMYaro** [comment] 2019-05-22 15:45
Partially addressed in https://github.com/ZMYaro/paintz/commit/e50a78329dc92b8dce87f86264df7e90eb4fcc8a.

**Comment by ZMYaro** [comment] 2019-05-22 15:47
The off-center shadows in Firefox appear to be a bug in Firefox with shadows on rounded elements, not a result of fractional shadows.
https://jsfiddle.net/fmvyroje/
https://stackoverflow.com/questions/55865490/box-shadow-on-div-with-border-radius-is-slightly-off-center

**Comment by ZMYaro** [comment] 2019-05-22 17:40
After testing on MacOS, it appears Safari displays the same shadow for any value < 1px, even on a Retina display, so it may be necessary to compromise here and not have 0.5px shadows anywhere.  (Chrome on MacOS looks fine, as expected, and Firefox actually looks OK on a Retina display).

**Comment by ZMYaro** [comment] 2019-05-22 21:19
Removed in https://github.com/ZMYaro/paintz/commit/8c3acbc8d8b4881048f90aa1435643baef71e729.

**Comment by ZMYaro** [comment] 2019-05-27 18:29
Firefox issue confirmed to be a bug in Firefox: 
![image](https://user-images.githubusercontent.com/763405/58434872-db537500-808b-11e9-9c09-aa9005109301.png)

**Comment by ZMYaro** [comment] 2019-08-01 16:19
Since this is fixed in other browsers, does not impede usability in Firefox, and the Firefox bug is filed, I am going to close this.

**Closed by ZMYaro** 2019-08-01 16:19 UTC
Labels: bug
