### ISSUE TITLE
can't save to network drive

### ISSUE THREAD

**Issue by rdragomir** [ZMYaro/paintz#162] opened 2020-05-04 05:39 UTC
**Describe the bug**
I have defined a network drive on my Chromebook in order to access my Synology NAS. 
Using PaintZ I can open a picture for editing. 

![Screenshot 2020-05-04 at 08 31 35](https://user-images.githubusercontent.com/14919471/80938452-db064280-8de1-11ea-9d61-972e0519838b.png)

When done I wanted to save it with a different name in the same folder on my network drive, but they are not visible anymore.

![Screenshot 2020-05-04 at 08 37 20](https://user-images.githubusercontent.com/14919471/80938646-9c24bc80-8de2-11ea-82d3-6df99a6f6c3b.png)

Can you fix that?

Thanks,
Radu

**Comment by ZMYaro** [comment] 2020-05-13 06:04
Hi Radu,

Unfortunately, PaintZ has no control over the Chrome OS save-as dialog.  I am not sure whether that limitation is being caused by Chrome OS or your NAS drive, but I do not see any way PaintZ could influence it.

Out of curiosity, if you right-click an image and select “Save image as”, do you have the issue?  Or if you right-click a link to an image and select “Save link as”?

**Comment by rdragomir** [comment] 2020-05-13 06:27
Hi,

i tried right-click on an image found on google.
it is the same. it doesn't show the LAN drives (see the attached screenshot).
probably this is the way Google tries to make users use Google Drive as network drive.

Maybe they will reconsider at some point and modify ChromeOS.

Thanks for trying,
Radu
     On Wednesday, May 13, 2020, 09:05:01 AM GMT+3, Zachary Yaro <notifications@github.com> wrote:  
 
 


Hi Radu,

Unfortunately, PaintZ has no control over the Chrome OS save-as dialog. I am not sure whether that limitation is being caused by Chrome OS or your NAS drive, but I do not see any way PaintZ could influence it.

Out of curiosity, if you right-click an image and select “Save image as”, do you have the issue? Or if you right-click a link to an image and select “Save link as”?

**Comment by ZMYaro** [comment] 2020-05-13 17:48
Thank you for checking.  Hopefully whatever limitation of Chrome OS or your NAS is causing that gets fixed in a future update; I am sorry I do not have the knowledge to help more 😕

**Closed** 2020-05-13 17:48 UTC
Labels: invalid
