### ISSUE TITLE
“Error 0 while attempting to load partials/toolbar/image.html”

### ISSUE THREAD

**Issue by pronoy2108** [ZMYaro/paintz#232] opened 2021-11-24 05:05 UTC
**Describe the bug**
[Error 0 while attempting to load partials/toolbar/image.html]

**Expected behavior**
[Page should have loaded the entire paintz source code]

**Actual behavior**
[Page didn't load the entire paintz source code due to an error]

**Screenshots**
[If applicable, add screenshots to help explain your problem.]
![image](https://user-images.githubusercontent.com/83197609/143177961-68790743-38ec-4654-806a-b6751bfb05b2.png)
![image](https://user-images.githubusercontent.com/83197609/143177966-0f4dc54a-0bdd-42eb-ab9d-ba186d800982.png)

**Environment**
 - Device: [e.g. Desktop PC]
 - OS: [Windows 11]
 - Browser: [e.g., Edge 96, Stable]

**Additional context**
[N/A]

**Comment by ZMYaro** [comment] 2021-11-29 02:27
As noted [in the readme](https://github.com/ZMYaro/paintz/blob/master/README.md#development-environment), PaintZ must be served from a web server to work.  Even a basic web server will work, but modern web browsers will not allow the necessary requests from JavaScript over `file:///`.

(I am happy to answer more questions, but I am closing this ticket because it is not a bug in PaintZ, just how web browsers have worked since a decade or so ago.)

**Closed by ZMYaro** 2021-11-29 02:27 UTC
Labels: bug
